import type { AutomaRegistry } from "@/types/automa";

export const automaRegistry: AutomaRegistry[] = [
  {
    id: "drift",
    slug: "drift",
    title: "Drift",
    theme: "Flow",
    description: "Calm drifting points with gentle directional flow",
    schema: [
      {
        key: "density",
        label: "Density",
        type: "slider",
        group: "Geometry",
        live: false,
        min: 50,
        max: 500,
        step: 10,
      },
      {
        key: "speed",
        label: "Speed",
        type: "slider",
        group: "Motion",
        live: true,
        min: 0.1,
        max: 5,
        step: 0.1,
      },
      {
        key: "direction",
        label: "Direction",
        type: "slider",
        group: "Motion",
        live: true,
        min: 0,
        max: 360,
        step: 1,
        unit: "°",
      },
      {
        key: "noise",
        label: "Noise Amount",
        type: "slider",
        group: "Motion",
        live: true,
        min: 0,
        max: 100,
        step: 1,
      },
      {
        key: "size",
        label: "Size",
        type: "slider",
        group: "Appearance",
        live: true,
        min: 1,
        max: 10,
        step: 0.5,
        unit: "px",
      },
      {
        key: "intensity",
        label: "Intensity",
        type: "slider",
        group: "Appearance",
        live: true,
        min: 0,
        max: 1,
        step: 0.05,
      },
    ],
    defaults: {
      density: 200,
      speed: 1,
      direction: 45,
      noise: 30,
      size: 2,
      intensity: 0.7,
    },
    renderer: {
      type: "component",
      component: "drift",
    },
  },
  {
    id: "lattice",
    slug: "lattice",
    title: "Lattice",
    theme: "Structure",
    description: "A geometric lattice that subtly breathes and deforms",
    schema: [
      {
        key: "spacing",
        label: "Spacing",
        type: "slider",
        group: "Geometry",
        live: false,
        min: 20,
        max: 100,
        step: 5,
        unit: "px",
      },
      {
        key: "deformation",
        label: "Deformation",
        type: "slider",
        group: "Motion",
        live: true,
        min: 0,
        max: 50,
        step: 1,
      },
      {
        key: "pulseSpeed",
        label: "Pulse Speed",
        type: "slider",
        group: "Timing",
        live: true,
        min: 0.1,
        max: 3,
        step: 0.1,
      },
      {
        key: "thickness",
        label: "Line Thickness",
        type: "slider",
        group: "Appearance",
        live: true,
        min: 0.5,
        max: 5,
        step: 0.5,
        unit: "px",
      },
      {
        key: "intensity",
        label: "Intensity",
        type: "slider",
        group: "Appearance",
        live: true,
        min: 0,
        max: 1,
        step: 0.05,
      },
    ],
    defaults: {
      spacing: 50,
      deformation: 15,
      pulseSpeed: 1,
      thickness: 1.5,
      intensity: 0.6,
    },
    renderer: {
      type: "component",
      component: "lattice",
    },
  },
  {
    id: "pulse",
    slug: "pulse",
    title: "Pulse",
    theme: "Rhythm",
    description: "Concentric rings that pulse rhythmically with falloff",
    schema: [
      {
        key: "rate",
        label: "Rate",
        type: "slider",
        group: "Timing",
        live: true,
        min: 0.1,
        max: 5,
        step: 0.1,
        unit: "Hz",
      },
      {
        key: "falloff",
        label: "Falloff",
        type: "slider",
        group: "Appearance",
        live: true,
        min: 0.1,
        max: 2,
        step: 0.1,
      },
      {
        key: "count",
        label: "Ring Count",
        type: "slider",
        group: "Geometry",
        live: false,
        min: 3,
        max: 20,
        step: 1,
      },
      {
        key: "thickness",
        label: "Thickness",
        type: "slider",
        group: "Appearance",
        live: true,
        min: 1,
        max: 10,
        step: 0.5,
        unit: "px",
      },
      {
        key: "intensity",
        label: "Intensity",
        type: "slider",
        group: "Appearance",
        live: true,
        min: 0,
        max: 1,
        step: 0.05,
      },
    ],
    defaults: {
      rate: 1,
      falloff: 0.8,
      count: 8,
      thickness: 3,
      intensity: 0.7,
    },
    renderer: {
      type: "component",
      component: "pulse",
    },
  },
  {
    id: "matrix-trails",
    slug: "matrix-trails",
    title: "Matrix Trails",
    theme: "Typography",
    description: "Dense rain of multilingual glyphs with mask highlights and twinkle wall.",
    schema: [
      // APPEARANCE
      {
        key: "outsideTrailColor",
        label: "Outside Trail Color",
        type: "color",
        group: "Appearance",
        live: true,
      },
      {
        key: "glowRadius",
        label: "Highlight Glow Radius",
        type: "slider",
        group: "Appearance",
        live: true,
        min: 0,
        max: 30,
        step: 1,
        unit: "px",
      },
      {
        key: "maskText",
        label: "Highlight Text",
        type: "text",
        group: "Appearance",
        live: true,
        placeholder: "你好",
      },
      {
        key: "accentColor",
        label: "Highlight Accent Color",
        type: "color",
        group: "Appearance",
        live: true,
      },
      {
        key: "wordFont",
        label: "Highlight Font",
        type: "select",
        group: "Appearance",
        live: true,
        options: [
          { label: "Serif", value: "serif" },
          { label: "Monospace", value: "mono" },
        ],
      },
      {
        key: "wordOpacity",
        label: "Highlight Opacity",
        type: "slider",
        group: "Appearance",
        live: true,
        min: 0,
        max: 1,
        step: 0.05,
      },
      {
        key: "backgroundColor",
        label: "Background Color",
        type: "color",
        group: "Appearance",
        live: true,
      },
      {
        key: "wallBrightness",
        label: "Wall Base Brightness",
        type: "slider",
        group: "Appearance",
        live: true,
        min: 0,
        max: 0.6,
        step: 0.01,
      },
      {
        key: "wallLift",
        label: "Wall Lift on Rain",
        type: "slider",
        group: "Appearance",
        live: true,
        min: 0,
        max: 0.2,
        step: 0.01,
      },

      // GRID SETUP
      {
        key: "cellSize",
        label: "Cell Size",
        type: "slider",
        group: "Geometry",
        live: false,
        min: 8,
        max: 32,
        step: 1,
        unit: "px",
      },
      {
        key: "fillMode",
        label: "Wall Fill Mode",
        type: "select",
        group: "Geometry",
        live: false,
        options: [
          { label: "Randomized", value: "random" },
          { label: "Fixed Text", value: "fixed" },
        ],
      },
      {
        key: "script",
        label: "Script",
        type: "select",
        group: "Geometry",
        live: false,
        visibleWhen: {
          key: "fillMode",
          value: "random",
        },
        options: [
          { label: "Alphabet", value: "alphabet" },
          { label: "Chinese", value: "chinese" },
          { label: "Japanese", value: "japanese" },
          { label: "Korean", value: "korean" },
        ],
      },
      {
        key: "fixedText",
        label: "Fixed Text",
        type: "text-array",
        group: "Geometry",
        live: false,
        visibleWhen: {
          key: "fillMode",
          value: "fixed",
        },
        placeholder: "你好世界",
      },
      {
        key: "textOrientation",
        label: "Text Orientation",
        type: "select",
        group: "Geometry",
        live: false,
        visibleWhen: {
          key: "fillMode",
          value: "fixed",
        },
        options: [
          { label: "Horizontal", value: "horizontal" },
          { label: "Vertical", value: "vertical" },
        ],
      },

      // RAIN BEHAVIOR
      {
        key: "rainSpeed",
        label: "Rain Speed",
        type: "slider",
        group: "Motion",
        live: true,
        min: 1,
        max: 60,
        step: 1,
        unit: "steps/sec",
      },
      {
        key: "outsideStrength",
        label: "Outside Trail Injection",
        type: "slider",
        group: "Motion",
        live: true,
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        key: "insideStrength",
        label: "Inside Trail Injection",
        type: "slider",
        group: "Motion",
        live: true,
        min: 0,
        max: 1,
        step: 0.01,
      },

      // TIMING
      {
        key: "outsideDecay",
        label: "Outside Fade Rate",
        type: "slider",
        group: "Timing",
        live: true,
        min: 0.5,
        max: 0.98,
        step: 0.01,
      },
      {
        key: "insideDecay",
        label: "Inside Fade Rate",
        type: "slider",
        group: "Timing",
        live: true,
        min: 0.5,
        max: 0.995,
        step: 0.005,
      },
      {
        key: "twinkleSpeed",
        label: "Twinkle Speed",
        type: "slider",
        group: "Timing",
        live: true,
        min: 0,
        max: 30,
        step: 1,
        unit: "FPS",
      },
    ],
    defaults: {
      cellSize: 16,
      fillMode: "random",
      script: "chinese",
      fixedText: ["你好世界"],
      textOrientation: "horizontal",
      rainSpeed: 12,
      outsideStrength: 0.18,
      insideStrength: 1.0,
      outsideDecay: 0.72,
      insideDecay: 0.9,
      outsideTrailColor: "#008c3c",
      glowRadius: 14,
      maskText: "你好",
      accentColor: "#86ffd0",
      wordFont: "serif",
      wordOpacity: 0.6,
      backgroundColor: "#000000",
      wallBrightness: 0.25,
      wallLift: 0.05,
      twinkleSpeed: 12,
    },
    renderer: {
      type: "component",
      component: "matrix-trails",
    },
  },
  {
    id: "shimmer-wall",
    slug: "shimmer-wall",
    title: "Shimmer Wall",
    theme: "Typography",
    description: "Rasterized word art with grid-based shimmer sweep and customizable gradient.",
    schema: [
      // APPEARANCE
      {
        key: "mainText",
        label: "Highlight Text",
        type: "text",
        group: "Appearance",
        live: true,
        placeholder: "你好",
      },
      {
        key: "bgB",
        label: "Wall Base Brightness",
        type: "slider",
        group: "Appearance",
        live: true,
        min: 0,
        max: 0.25,
        step: 0.01,
      },
      {
        key: "baseB",
        label: "Highlight Base Brightness",
        type: "slider",
        group: "Appearance",
        live: true,
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        key: "peakB",
        label: "Highlight Peak Brightness",
        type: "slider",
        group: "Appearance",
        live: true,
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        key: "gradientStops",
        label: "Sweep Gradient Profile",
        type: "gradient",
        group: "Appearance",
        live: true,
        inlineToggle: {
          key: "lockEnds",
          label: "Lock Ends",
        },
      },
      {
        key: "lockEnds",
        label: "Lock Gradient Ends at 0",
        type: "toggle",
        group: "Appearance",
        live: true,
      },
      {
        key: "backgroundColor",
        label: "Background Color",
        type: "color",
        group: "Appearance",
        live: true,
      },
      {
        key: "textColor",
        label: "Text Color",
        type: "color",
        group: "Appearance",
        live: true,
      },

      // GRID SETUP
      {
        key: "cellSize",
        label: "Cell Size",
        type: "slider",
        group: "Geometry",
        live: false,
        min: 8,
        max: 32,
        step: 1,
        unit: "px",
      },
      {
        key: "fillMode",
        label: "Wall Fill Mode",
        type: "select",
        group: "Geometry",
        live: false,
        options: [
          { label: "Randomized", value: "random" },
          { label: "Fixed Text", value: "fixed" },
        ],
      },
      {
        key: "lang",
        label: "Script",
        type: "select",
        group: "Geometry",
        live: false,
        visibleWhen: {
          key: "fillMode",
          value: "random",
        },
        options: [
          { label: "Alphabet", value: "alphabet" },
          { label: "Chinese", value: "chinese" },
          { label: "Japanese", value: "japanese" },
          { label: "Korean", value: "korean" },
        ],
      },
      {
        key: "fixedText",
        label: "Fixed Text",
        type: "text-array",
        group: "Geometry",
        live: false,
        visibleWhen: {
          key: "fillMode",
          value: "fixed",
        },
        placeholder: "你好世界",
      },
      {
        key: "textOrientation",
        label: "Text Orientation",
        type: "select",
        group: "Geometry",
        live: false,
        visibleWhen: {
          key: "fillMode",
          value: "fixed",
        },
        options: [
          { label: "Horizontal", value: "horizontal" },
          { label: "Vertical", value: "vertical" },
        ],
      },

      // MOTION
      {
        key: "speed",
        label: "Sweep Period",
        type: "slider",
        group: "Motion",
        live: true,
        min: 1,
        max: 20,
        step: 1,
        unit: "s",
      },
      {
        key: "sweepHalfWidth",
        label: "Sweep Half-Width",
        type: "slider",
        group: "Motion",
        live: true,
        min: 0.05,
        max: 0.5,
        step: 0.01,
      },
    ],
    defaults: {
      cellSize: 16,
      fillMode: "random",
      lang: "chinese",
      fixedText: ["你好世界"],
      textOrientation: "horizontal",
      mainText: "你好",
      speed: 6,
      sweepHalfWidth: 0.22,
      bgB: 0.06,
      baseB: 0.12,
      peakB: 1.0,
      wallSweep: false,
      wallSweepStrength: 0.3,
      lockEnds: true,
      gradientStops: '[{"p":0,"v":0},{"p":0.2,"v":0.1},{"p":0.5,"v":0.8},{"p":0.8,"v":0.1},{"p":1,"v":0}]',
      backgroundColor: "#000000",
      textColor: "#ffffff",
    },
    renderer: {
      type: "component",
      component: "shimmer-wall",
    },
  },
  {
    id: "sweep-highlight",
    slug: "sweep-highlight",
    title: "Sweep Highlight",
    theme: "Typography",
    description: "Grid-based wall with traveling sweep highlight and pinned serif word.",
    schema: [
      // APPEARANCE
      {
        key: "largeText",
        label: "Highlight Text",
        type: "text",
        group: "Appearance",
        live: true,
        placeholder: "你好",
      },
      {
        key: "highlightOpacity",
        label: "Highlight Opacity",
        type: "slider",
        group: "Appearance",
        live: true,
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        key: "wallBase",
        label: "Wall Base Brightness",
        type: "slider",
        group: "Appearance",
        live: true,
        min: 0,
        max: 0.25,
        step: 0.01,
      },
      {
        key: "wallPeak",
        label: "Wall Peak Brightness",
        type: "slider",
        group: "Appearance",
        live: true,
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        key: "gradientStops",
        label: "Sweep Gradient Profile",
        type: "gradient",
        group: "Appearance",
        live: true,
        inlineToggle: {
          key: "lockEnds",
          label: "Lock Ends",
        },
      },
      {
        key: "lockEnds",
        label: "Lock Gradient Ends at 0",
        type: "toggle",
        group: "Appearance",
        live: true,
      },
      {
        key: "backgroundColor",
        label: "Background Color",
        type: "color",
        group: "Appearance",
        live: true,
      },
      {
        key: "textColor",
        label: "Text Color",
        type: "color",
        group: "Appearance",
        live: true,
      },

      // GRID SETUP
      {
        key: "cellSize",
        label: "Cell Size",
        type: "slider",
        group: "Geometry",
        live: false,
        min: 8,
        max: 32,
        step: 1,
        unit: "px",
      },
      {
        key: "bgType",
        label: "Wall Fill Mode",
        type: "select",
        group: "Geometry",
        live: false,
        options: [
          { label: "Randomized", value: "random" },
          { label: "Fixed Text", value: "fixed" },
        ],
      },
      {
        key: "lang",
        label: "Script",
        type: "select",
        group: "Geometry",
        live: false,
        visibleWhen: {
          key: "bgType",
          value: "random",
        },
        options: [
          { label: "Alphabet", value: "alphabet" },
          { label: "Chinese", value: "chinese" },
          { label: "Japanese", value: "japanese" },
          { label: "Korean", value: "korean" },
        ],
      },
      {
        key: "fixedText",
        label: "Fixed Text",
        type: "text-array",
        group: "Geometry",
        live: false,
        visibleWhen: {
          key: "bgType",
          value: "fixed",
        },
        placeholder: "你好世界",
      },
      {
        key: "textOrientation",
        label: "Text Orientation",
        type: "select",
        group: "Geometry",
        live: false,
        visibleWhen: {
          key: "bgType",
          value: "fixed",
        },
        options: [
          { label: "Horizontal", value: "horizontal" },
          { label: "Vertical", value: "vertical" },
        ],
      },

      // MOTION
      {
        key: "speed",
        label: "Sweep Period",
        type: "slider",
        group: "Motion",
        live: true,
        min: 2,
        max: 30,
        step: 1,
        unit: "s",
      },
      {
        key: "halfW",
        label: "Sweep Half-Width",
        type: "slider",
        group: "Motion",
        live: true,
        min: 0.05,
        max: 0.6,
        step: 0.01,
      },
    ],
    defaults: {
      cellSize: 16,
      bgType: "random",
      lang: "chinese",
      fixedText: ["你好世界"],
      textOrientation: "horizontal",
      largeText: "你好",
      highlightOpacity: 0.98,
      speed: 10,
      halfW: 0.26,
      wallBase: 0.08,
      wallPeak: 0.65,
      gradientStops: '[{"p":0,"v":0},{"p":0.15,"v":0.1},{"p":0.5,"v":0.8},{"p":0.85,"v":0.1},{"p":1,"v":0}]',
      lockEnds: true,
      backgroundColor: "#000000",
      textColor: "#ffffff",
    },
    renderer: {
      type: "component",
      component: "sweep-highlight",
    },
  },
];

// Helper functions
export function getAutomaBySlug(slug: string): AutomaRegistry | undefined {
  return automaRegistry.find((a) => a.slug === slug);
}

export function getAutomaByTheme(theme: string) {
  return automaRegistry.filter((a) => a.theme === theme);
}

export function getAllThemes(): string[] {
  return Array.from(new Set(automaRegistry.map((a) => a.theme)));
}
