import type { AutomaRegistry } from "@/types/automa";

export const automaRegistry: AutomaRegistry[] = [
  {
    id: "drift",
    slug: "drift",
    title: "Drift",
    theme: "Flow",
    description: "Calm drifting points with gentle directional flow",
    schema: [
      {
        key: "density",
        label: "Density",
        type: "slider",
        group: "Geometry",
        live: false,
        min: 50,
        max: 500,
        step: 10,
      },
      {
        key: "speed",
        label: "Speed",
        type: "slider",
        group: "Motion",
        live: true,
        min: 0.1,
        max: 5,
        step: 0.1,
      },
      {
        key: "direction",
        label: "Direction",
        type: "slider",
        group: "Motion",
        live: true,
        min: 0,
        max: 360,
        step: 1,
        unit: "°",
      },
      {
        key: "noise",
        label: "Noise Amount",
        type: "slider",
        group: "Motion",
        live: true,
        min: 0,
        max: 100,
        step: 1,
      },
      {
        key: "size",
        label: "Size",
        type: "slider",
        group: "Appearance",
        live: true,
        min: 1,
        max: 10,
        step: 0.5,
        unit: "px",
      },
      {
        key: "intensity",
        label: "Intensity",
        type: "slider",
        group: "Appearance",
        live: true,
        min: 0,
        max: 1,
        step: 0.05,
      },
    ],
    defaults: {
      density: 200,
      speed: 1,
      direction: 45,
      noise: 30,
      size: 2,
      intensity: 0.7,
    },
    renderer: {
      type: "component",
      component: "drift",
    },
  },
  {
    id: "lattice",
    slug: "lattice",
    title: "Lattice",
    theme: "Structure",
    description: "A geometric lattice that subtly breathes and deforms",
    schema: [
      {
        key: "spacing",
        label: "Spacing",
        type: "slider",
        group: "Geometry",
        live: false,
        min: 20,
        max: 100,
        step: 5,
        unit: "px",
      },
      {
        key: "deformation",
        label: "Deformation",
        type: "slider",
        group: "Motion",
        live: true,
        min: 0,
        max: 50,
        step: 1,
      },
      {
        key: "pulseSpeed",
        label: "Pulse Speed",
        type: "slider",
        group: "Timing",
        live: true,
        min: 0.1,
        max: 3,
        step: 0.1,
      },
      {
        key: "thickness",
        label: "Line Thickness",
        type: "slider",
        group: "Appearance",
        live: true,
        min: 0.5,
        max: 5,
        step: 0.5,
        unit: "px",
      },
      {
        key: "intensity",
        label: "Intensity",
        type: "slider",
        group: "Appearance",
        live: true,
        min: 0,
        max: 1,
        step: 0.05,
      },
    ],
    defaults: {
      spacing: 50,
      deformation: 15,
      pulseSpeed: 1,
      thickness: 1.5,
      intensity: 0.6,
    },
    renderer: {
      type: "component",
      component: "lattice",
    },
  },
  {
    id: "pulse",
    slug: "pulse",
    title: "Pulse",
    theme: "Rhythm",
    description: "Concentric rings that pulse rhythmically with falloff",
    schema: [
      {
        key: "rate",
        label: "Rate",
        type: "slider",
        group: "Timing",
        live: true,
        min: 0.1,
        max: 5,
        step: 0.1,
        unit: "Hz",
      },
      {
        key: "falloff",
        label: "Falloff",
        type: "slider",
        group: "Appearance",
        live: true,
        min: 0.1,
        max: 2,
        step: 0.1,
      },
      {
        key: "count",
        label: "Ring Count",
        type: "slider",
        group: "Geometry",
        live: false,
        min: 3,
        max: 20,
        step: 1,
      },
      {
        key: "thickness",
        label: "Thickness",
        type: "slider",
        group: "Appearance",
        live: true,
        min: 1,
        max: 10,
        step: 0.5,
        unit: "px",
      },
      {
        key: "intensity",
        label: "Intensity",
        type: "slider",
        group: "Appearance",
        live: true,
        min: 0,
        max: 1,
        step: 0.05,
      },
    ],
    defaults: {
      rate: 1,
      falloff: 0.8,
      count: 8,
      thickness: 3,
      intensity: 0.7,
    },
    renderer: {
      type: "component",
      component: "pulse",
    },
  },
];

// Helper functions
export function getAutomaBySlug(slug: string): AutomaRegistry | undefined {
  return automaRegistry.find((a) => a.slug === slug);
}

export function getAutomaByTheme(theme: string) {
  return automaRegistry.filter((a) => a.theme === theme);
}

export function getAllThemes(): string[] {
  return Array.from(new Set(automaRegistry.map((a) => a.theme)));
}
